# Generated by Django 6.0.7 on 2026-07-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_userpost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, help_text='200 charectors only allowed.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.TextField(help_text='500 charectors only allowed.', max_length=500),
        ),
    ]
