# Generated by Django 6.0.7 on 2026-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userpost_title_alter_userpost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_edited',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.usercomment'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, default='', help_text='200 charectors only allowed.', max_length=200),
        ),
    ]
