# Generated by Django 6.0.7 on 2026-07-26 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_userpost_is_edited_alter_userpost_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='comment_text',
            field=models.TextField(blank=True, help_text='500 charectors only allowed.', max_length=500),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='is_edited',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.userpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlike',
            name='is_edited',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userlike',
            name='likes',
            field=models.IntegerField(blank=True, default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='post',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.userpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
