# Generated by Django 6.0.7 on 2026-07-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_userpost_comments_remove_userpost_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='likes',
        ),
    ]
